### ISSUE TITLE
Compiled into exe or...?

### ISSUE THREAD

**Issue by hoseyjoe** [larsiusprime/firetongue#26]
It looks like all targets have  "assets" folder next to compile (exe or html) except flash.  Is there a way to easily compile assets into JS/EXE ?

**Comment by larsiusprime** [comment]
This is more of a general OpenFL/NME usage issue than a firetongue issue. IIRC, you can set your assets to be embedded rather than loaded from disk, in which case they will be packaged inside your executable itself, or in the case of JS, I believe internally packaged up as hard-coded Base64-encoded strings. 

If I'm not mistaken about all this (which I might be), you can set this "embedded = true" flag somewhere, and the traditional OpenFL/NME asset pipeline still works the same way, it just changes how the assets are stored. I would ask someone in the OpenFL community about this pipeline.

**Comment by hoseyjoe** [comment]
Thank you.
